//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	rkecattleiov1 "github.com/rancher/rancher/pkg/apis/rke.cattle.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Beacon) DeepCopyInto(out *Beacon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Beacon.
func (in *Beacon) DeepCopy() *Beacon {
	if in == nil {
		return nil
	}
	out := new(Beacon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Beacon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconAcquisitionRequest) DeepCopyInto(out *BeaconAcquisitionRequest) {
	*out = *in
	out.ClusterPlan = in.ClusterPlan
	out.Lifecycle = in.Lifecycle
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconAcquisitionRequest.
func (in *BeaconAcquisitionRequest) DeepCopy() *BeaconAcquisitionRequest {
	if in == nil {
		return nil
	}
	out := new(BeaconAcquisitionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconCancellation) DeepCopyInto(out *BeaconCancellation) {
	*out = *in
	out.PreemptingPlan = in.PreemptingPlan
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconCancellation.
func (in *BeaconCancellation) DeepCopy() *BeaconCancellation {
	if in == nil {
		return nil
	}
	out := new(BeaconCancellation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconHolder) DeepCopyInto(out *BeaconHolder) {
	*out = *in
	out.Name = in.Name
	in.AcquiredAt.DeepCopyInto(&out.AcquiredAt)
	in.DeadlineAt.DeepCopyInto(&out.DeadlineAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconHolder.
func (in *BeaconHolder) DeepCopy() *BeaconHolder {
	if in == nil {
		return nil
	}
	out := new(BeaconHolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconList) DeepCopyInto(out *BeaconList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Beacon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconList.
func (in *BeaconList) DeepCopy() *BeaconList {
	if in == nil {
		return nil
	}
	out := new(BeaconList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeaconList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconSpec) DeepCopyInto(out *BeaconSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Acquisition != nil {
		in, out := &in.Acquisition, &out.Acquisition
		*out = new(BeaconAcquisitionRequest)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconSpec.
func (in *BeaconSpec) DeepCopy() *BeaconSpec {
	if in == nil {
		return nil
	}
	out := new(BeaconSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeaconStatus) DeepCopyInto(out *BeaconStatus) {
	*out = *in
	if in.ActiveSelectors != nil {
		in, out := &in.ActiveSelectors, &out.ActiveSelectors
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Holder != nil {
		in, out := &in.Holder, &out.Holder
		*out = new(BeaconHolder)
		(*in).DeepCopyInto(*out)
	}
	if in.Cancellation != nil {
		in, out := &in.Cancellation, &out.Cancellation
		*out = new(BeaconCancellation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeaconStatus.
func (in *BeaconStatus) DeepCopy() *BeaconStatus {
	if in == nil {
		return nil
	}
	out := new(BeaconStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlan) DeepCopyInto(out *ClusterPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlan.
func (in *ClusterPlan) DeepCopy() *ClusterPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanList) DeepCopyInto(out *ClusterPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanList.
func (in *ClusterPlanList) DeepCopy() *ClusterPlanList {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanSpec) DeepCopyInto(out *ClusterPlanSpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalClusterScopedRef)
		**out = **in
	}
	out.ClusterRef = in.ClusterRef
	if in.EntrypointRef != nil {
		in, out := &in.EntrypointRef, &out.EntrypointRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = make([]NodePoolPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]NodePoolFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = make([]NodePoolProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = make([]NodePoolInstruction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Lifecycle = in.Lifecycle
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanSpec.
func (in *ClusterPlanSpec) DeepCopy() *ClusterPlanSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanStatus) DeepCopyInto(out *ClusterPlanStatus) {
	*out = *in
	if in.PersistentOutputs != nil {
		in, out := &in.PersistentOutputs, &out.PersistentOutputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanStatus.
func (in *ClusterPlanStatus) DeepCopy() *ClusterPlanStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanTemplate) DeepCopyInto(out *ClusterPlanTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanTemplate.
func (in *ClusterPlanTemplate) DeepCopy() *ClusterPlanTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlanTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanTemplateList) DeepCopyInto(out *ClusterPlanTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPlanTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanTemplateList.
func (in *ClusterPlanTemplateList) DeepCopy() *ClusterPlanTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlanTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanTemplateSpec) DeepCopyInto(out *ClusterPlanTemplateSpec) {
	*out = *in
	if in.Entrypoints != nil {
		in, out := &in.Entrypoints, &out.Entrypoints
		*out = make([]EntrypointRef, len(*in))
		copy(*out, *in)
	}
	out.Lifecycle = in.Lifecycle
	if in.NodePlanTemplates != nil {
		in, out := &in.NodePlanTemplates, &out.NodePlanTemplates
		*out = make([]LocalClusterScopedRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanTemplateSpec.
func (in *ClusterPlanTemplateSpec) DeepCopy() *ClusterPlanTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlanTemplateStatus) DeepCopyInto(out *ClusterPlanTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlanTemplateStatus.
func (in *ClusterPlanTemplateStatus) DeepCopy() *ClusterPlanTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPlanTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDSnapshotCreate) DeepCopyInto(out *ETCDSnapshotCreate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDSnapshotCreate.
func (in *ETCDSnapshotCreate) DeepCopy() *ETCDSnapshotCreate {
	if in == nil {
		return nil
	}
	out := new(ETCDSnapshotCreate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ETCDSnapshotCreate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDSnapshotCreateList) DeepCopyInto(out *ETCDSnapshotCreateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ETCDSnapshotCreate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDSnapshotCreateList.
func (in *ETCDSnapshotCreateList) DeepCopy() *ETCDSnapshotCreateList {
	if in == nil {
		return nil
	}
	out := new(ETCDSnapshotCreateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ETCDSnapshotCreateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDSnapshotCreateSpec) DeepCopyInto(out *ETCDSnapshotCreateSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(rkecattleiov1.ETCDSnapshotS3)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDSnapshotCreateSpec.
func (in *ETCDSnapshotCreateSpec) DeepCopy() *ETCDSnapshotCreateSpec {
	if in == nil {
		return nil
	}
	out := new(ETCDSnapshotCreateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDSnapshotCreateStatus) DeepCopyInto(out *ETCDSnapshotCreateStatus) {
	*out = *in
	if in.ClusterPlanRef != nil {
		in, out := &in.ClusterPlanRef, &out.ClusterPlanRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDSnapshotCreateStatus.
func (in *ETCDSnapshotCreateStatus) DeepCopy() *ETCDSnapshotCreateStatus {
	if in == nil {
		return nil
	}
	out := new(ETCDSnapshotCreateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntrypointRef) DeepCopyInto(out *EntrypointRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntrypointRef.
func (in *EntrypointRef) DeepCopy() *EntrypointRef {
	if in == nil {
		return nil
	}
	out := new(EntrypointRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *File) DeepCopyInto(out *File) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new File.
func (in *File) DeepCopy() *File {
	if in == nil {
		return nil
	}
	out := new(File)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPGetAction) DeepCopyInto(out *HTTPGetAction) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPGetAction.
func (in *HTTPGetAction) DeepCopy() *HTTPGetAction {
	if in == nil {
		return nil
	}
	out := new(HTTPGetAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instruction) DeepCopyInto(out *Instruction) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Strategy = in.Strategy
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instruction.
func (in *Instruction) DeepCopy() *Instruction {
	if in == nil {
		return nil
	}
	out := new(Instruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstructionStrategy) DeepCopyInto(out *InstructionStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstructionStrategy.
func (in *InstructionStrategy) DeepCopy() *InstructionStrategy {
	if in == nil {
		return nil
	}
	out := new(InstructionStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONPatch) DeepCopyInto(out *JSONPatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatch.
func (in *JSONPatch) DeepCopy() *JSONPatch {
	if in == nil {
		return nil
	}
	out := new(JSONPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalClusterScopedRef) DeepCopyInto(out *LocalClusterScopedRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalClusterScopedRef.
func (in *LocalClusterScopedRef) DeepCopy() *LocalClusterScopedRef {
	if in == nil {
		return nil
	}
	out := new(LocalClusterScopedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeElection) DeepCopyInto(out *NodeElection) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeElection.
func (in *NodeElection) DeepCopy() *NodeElection {
	if in == nil {
		return nil
	}
	out := new(NodeElection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlan) DeepCopyInto(out *NodePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlan.
func (in *NodePlan) DeepCopy() *NodePlan {
	if in == nil {
		return nil
	}
	out := new(NodePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanList) DeepCopyInto(out *NodePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanList.
func (in *NodePlanList) DeepCopy() *NodePlanList {
	if in == nil {
		return nil
	}
	out := new(NodePlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanSpec) DeepCopyInto(out *NodePlanSpec) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]File, len(*in))
		copy(*out, *in)
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = make([]Instruction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = make([]Probe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]Output, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanSpec.
func (in *NodePlanSpec) DeepCopy() *NodePlanSpec {
	if in == nil {
		return nil
	}
	out := new(NodePlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanStatus) DeepCopyInto(out *NodePlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(map[string]OutputStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanStatus.
func (in *NodePlanStatus) DeepCopy() *NodePlanStatus {
	if in == nil {
		return nil
	}
	out := new(NodePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanTemplate) DeepCopyInto(out *NodePlanTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanTemplate.
func (in *NodePlanTemplate) DeepCopy() *NodePlanTemplate {
	if in == nil {
		return nil
	}
	out := new(NodePlanTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePlanTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanTemplateList) DeepCopyInto(out *NodePlanTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePlanTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanTemplateList.
func (in *NodePlanTemplateList) DeepCopy() *NodePlanTemplateList {
	if in == nil {
		return nil
	}
	out := new(NodePlanTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePlanTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanTemplateSpec) DeepCopyInto(out *NodePlanTemplateSpec) {
	*out = *in
	if in.SourceOfTruths != nil {
		in, out := &in.SourceOfTruths, &out.SourceOfTruths
		*out = make([]NodeSourceOfTruth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanTemplateSpec.
func (in *NodePlanTemplateSpec) DeepCopy() *NodePlanTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(NodePlanTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlanTemplateStatus) DeepCopyInto(out *NodePlanTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlanTemplateStatus.
func (in *NodePlanTemplateStatus) DeepCopy() *NodePlanTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(NodePlanTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolConcurrency) DeepCopyInto(out *NodePoolConcurrency) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Concurrency = in.Concurrency
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolConcurrency.
func (in *NodePoolConcurrency) DeepCopy() *NodePoolConcurrency {
	if in == nil {
		return nil
	}
	out := new(NodePoolConcurrency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolFile) DeepCopyInto(out *NodePoolFile) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolFile.
func (in *NodePoolFile) DeepCopy() *NodePoolFile {
	if in == nil {
		return nil
	}
	out := new(NodePoolFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolInstruction) DeepCopyInto(out *NodePoolInstruction) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Instruction.DeepCopyInto(&out.Instruction)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolInstruction.
func (in *NodePoolInstruction) DeepCopy() *NodePoolInstruction {
	if in == nil {
		return nil
	}
	out := new(NodePoolInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolPlan) DeepCopyInto(out *NodePoolPlan) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Election != nil {
		in, out := &in.Election, &out.Election
		*out = new(NodeElection)
		(*in).DeepCopyInto(*out)
	}
	in.Patches.DeepCopyInto(&out.Patches)
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.NodePlanTemplateRef != nil {
		in, out := &in.NodePlanTemplateRef, &out.NodePlanTemplateRef
		*out = new(LocalClusterScopedRef)
		**out = **in
	}
	in.NodePlanSpec.DeepCopyInto(&out.NodePlanSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolPlan.
func (in *NodePoolPlan) DeepCopy() *NodePoolPlan {
	if in == nil {
		return nil
	}
	out := new(NodePoolPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolProbe) DeepCopyInto(out *NodePoolProbe) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]v1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Probe.DeepCopyInto(&out.Probe)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolProbe.
func (in *NodePoolProbe) DeepCopy() *NodePoolProbe {
	if in == nil {
		return nil
	}
	out := new(NodePoolProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSourceOfTruth) DeepCopyInto(out *NodeSourceOfTruth) {
	*out = *in
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]EntrypointRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSourceOfTruth.
func (in *NodeSourceOfTruth) DeepCopy() *NodeSourceOfTruth {
	if in == nil {
		return nil
	}
	out := new(NodeSourceOfTruth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationLifecycle) DeepCopyInto(out *OperationLifecycle) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationLifecycle.
func (in *OperationLifecycle) DeepCopy() *OperationLifecycle {
	if in == nil {
		return nil
	}
	out := new(OperationLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Output) DeepCopyInto(out *Output) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Output.
func (in *Output) DeepCopy() *Output {
	if in == nil {
		return nil
	}
	out := new(Output)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputStatus) DeepCopyInto(out *OutputStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputStatus.
func (in *OutputStatus) DeepCopy() *OutputStatus {
	if in == nil {
		return nil
	}
	out := new(OutputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	if in.Definitions != nil {
		in, out := &in.Definitions, &out.Definitions
		*out = make([]PatchDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinition) DeepCopyInto(out *PatchDefinition) {
	*out = *in
	out.Selector = in.Selector
	if in.JSONPatches != nil {
		in, out := &in.JSONPatches, &out.JSONPatches
		*out = make([]JSONPatch, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinition.
func (in *PatchDefinition) DeepCopy() *PatchDefinition {
	if in == nil {
		return nil
	}
	out := new(PatchDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchSelector) DeepCopyInto(out *PatchSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchSelector.
func (in *PatchSelector) DeepCopy() *PatchSelector {
	if in == nil {
		return nil
	}
	out := new(PatchSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patches) DeepCopyInto(out *Patches) {
	*out = *in
	if in.Before != nil {
		in, out := &in.Before, &out.Before
		*out = make([]Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = make([]Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patches.
func (in *Patches) DeepCopy() *Patches {
	if in == nil {
		return nil
	}
	out := new(Patches)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
	out.RetryStrategy = in.RetryStrategy
	if in.HTTPGetAction != nil {
		in, out := &in.HTTPGetAction, &out.HTTPGetAction
		*out = new(HTTPGetAction)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeStrategy) DeepCopyInto(out *ProbeStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeStrategy.
func (in *ProbeStrategy) DeepCopy() *ProbeStrategy {
	if in == nil {
		return nil
	}
	out := new(ProbeStrategy)
	in.DeepCopyInto(out)
	return out
}
