package configserver

import (
	"net/http"
	"strings"

	mgmtcontrollers "github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3"
	"github.com/sirupsen/logrus"
)

type customServer struct {
	clusterTokenCache mgmtcontrollers.ClusterRegistrationTokenCache
}

func (s *customServer) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	switch req.URL.Path {
	case "v1/custom/register":
		s.register(rw, req)
	}
}

type CustomMachineRegistration struct {
	MachineID string `json:"machineId"`
	
	NodeName string `json:"nodeName"`

	Labels      map[string]string `json:"labels"`
	Annotations map[string]string `json:"annotations"`
}

// register receives a request when a user registers a custom node (at `/v1/custom/register`) and will return the
// system-agent installation script for the node.
// The `X-Cattle-Id` is randomly generated by the node and is expected to be unique across machines.
// The `/v1/custom/register` endpoint is idempotent and will return the system-agent installation script for a given
// machine id as long as the cluster registration token is valid.
// Custom node registration can be enabled/disabled by setting the RKEControlPlane's `spec.custom.enabled` field
// accordingly.
// The `X-Cattle-Token` header contains the sha256sum of the ClusterRegistrationToken. If this token is invalidated, new
// machines attempting to join with this token will be rejected.
func (s *customServer) register(rw http.ResponseWriter, req *http.Request) {
	machineID := req.Header.Get("X-Cattle-Id")
	logrus.Debugf("[customserver] parsed %s as machineID", machineID)
	if machineID == "" {
		rw.WriteHeader(http.StatusUnauthorized)
		return
	}

	token := strings.TrimPrefix(req.Header.Get("Authorization"), "Bearer ")
	if token == "" {
		logrus.Tracef("[customserver] no token found in request")
		rw.WriteHeader(http.StatusUnauthorized)
		return
	}

	tokens, err := s.clusterTokenCache.GetByIndex(tokenIndex, token)
	if err != nil {
		http.Error(rw, err.Error(), http.StatusInternalServerError)
		return
	}

	if len(tokens) == 0 {
		logrus.Tracef("[customserver] no cluster registration token found")
		rw.WriteHeader(http.StatusUnauthorized)
		return
	}

	data := dataFromHeaders(req)

	// create machine request

	// wait for it to be ready

}
