apiVersion: plan.cattle.io/v1alpha1
kind: ClusterPlan
metadata:
  namespace: fleet-default
  name: jhyde-rke2-test-cluster-plan
spec:
  plan:
    - selector:
        matchExpressions:
          - key: rke.cattle.io/etcd-role
            operator: In
            values: [ "true" ]
      instructions:
        - name: 'Create snapshot'
          command: rke2
          args: [ 'etcd-snapshot', 'save' ]
        - name: 'Restart service'
          command: systemctl
          args: [ 'restart', 'rke2-server' ]
      patches:
        before:
          - name: pauseCluster
            definitions:
              - selector:
                  apiVersion: cluster.x-k8s.io/v1beta2
                  kind: Cluster
                  namespace: fleet-default
                  name: jhyde-rke2-test
                jsonPatches:
                  op: add
                  path: "/spec/paused"
                  value: true
        after:
          - name: unpauseCluster
            definitions:
              - selector:
                  apiVersion: cluster.x-k8s.io/v1beta2
                  kind: Cluster
                  namespace: fleet-default
                  name: jhyde-rke2-test
                jsonPatches:
                  op: add
                  path: "/spec/paused"
                  value: false