apiVersion: plan.cattle.io/v1alpha1
kind: ClusterPlanTemplate
metadata:
  name: etcd-snapshot-create-caprke2
  labels:
    plan.cattle.io/builtin: "true"
spec:
  operation: etcd-snapshot-create
  entrypoints:
    - apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlane
  lifecycle:
    cancellable: false
    cancelsOthers: false
    timeoutSeconds: 1800
  plan: |
    plan:
      - name: snapshot
        selector:
          matchLabels:
            rke.cattle.io/etcd-role: "true"
        concurrency: -1
        instructions:
          - name: create
            command: rke2
            args:
              - etcd-snapshot
              - save
              {{- with index .Inputs "snapshotName" }}
              - --name
              - "{{ . }}"
              {{- end }}
            saveOutput: true
        outputs:
          - name: snapshot-stdout
            source: create
            persistent: true
